### ISSUE TITLE
Is it possible to disable enchantments?

### ISSUE THREAD

**Issue by ak4776955** [RealTriassic/RandomCart#1]
Players should destroy blocks to have a chance of spawning them, but silk will also have an effect, and hopefully the enchantment will be freely configurable in the config to enable and disable it.

**Comment by RealTriassic** [comment]
Hello, yes, I'll be adding a configuration option for this soon, thank you very much for telling me about this

**Comment by RealTriassic** [comment]
Implemented in https://github.com/StupidCraft/RandomCart/commit/1f216d464dedf9d376ac540617fc5a949710e055.
